### ISSUE TITLE
can't delete folder after build

### ISSUE THREAD

**Issue by julienhmmt** [stylersnico/nginx-openssl-chacha-naxsi#18]
after using the script, the work folder have to be delete. However, it can't be deleted : 

`        || mkdir -p '/var/log/nginx'
make[1]: Leaving directory '/usr/src/nginx-1.19.9'
rm: cannot remove 'nginx': No such file or directory
`
The folder is not 'nginx' but 'nginx-[version_number]'. I'm working on a fix... ;-)

**Comment by stylersnico** [comment]
Please PR with the fix
