### ISSUE TITLE
Problem to update nginx to 1.11.5

### ISSUE THREAD

**Issue by ghost** [stylersnico/nginx-openssl-chacha-naxsi#9]
objs/Makefile:920: recipe for target 'objs/src/event/ngx_event_openssl.o' failed
make[1]: **\* [objs/src/event/ngx_event_openssl.o] Error 1
make[1]: Leaving directory '/usr/src/nginx-1.11.5'
Makefile:8: recipe for target 'build' failed
make: **\* [build] Error 2
make -f objs/Makefile install
make[1]: Entering directory '/usr/src/nginx-1.11.5'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/src/openssl-1.1.0b/.openssl/include -I /usr/include/libxml2 -I objs \
    -o objs/src/event/ngx_event_openssl.o \
    src/event/ngx_event_openssl.c
src/event/ngx_event_openssl.c: In function 'ngx_ssl_create_connection':
src/event/ngx_event_openssl.c:1134:7: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec'
     sc->dyn_rec = ssl->dyn_rec;
       ^
src/event/ngx_event_openssl.c:1134:22: error: 'ngx_ssl_t' has no member named 'dyn_rec'
     sc->dyn_rec = ssl->dyn_rec;
                      ^
src/event/ngx_event_openssl.c: In function 'ngx_ssl_send_chain':
src/event/ngx_event_openssl.c:1683:19: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec'
         if (c->ssl->dyn_rec.timeout > 0 ) {
                   ^
src/event/ngx_event_openssl.c:1685:42: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec_last_write'
             if (ngx_current_msec - c->ssl->dyn_rec_last_write >
                                          ^
src/event/ngx_event_openssl.c:1686:23: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec'
                 c->ssl->dyn_rec.timeout)
                       ^
src/event/ngx_event_openssl.c:1688:47: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec'
                 buf->end = buf->start + c->ssl->dyn_rec.size_lo;
                                               ^
src/event/ngx_event_openssl.c:1689:23: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec_records_sent'
                 c->ssl->dyn_rec_records_sent = 0;
                       ^
src/event/ngx_event_openssl.c:1692:27: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec_records_sent'
                 if (c->ssl->dyn_rec_records_sent >
                           ^
src/event/ngx_event_openssl.c:1693:27: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec'
                     c->ssl->dyn_rec.threshold \* 2)
                           ^
src/event/ngx_event_openssl.c:1697:34: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec_records_sent'
                 } else if (c->ssl->dyn_rec_records_sent >
                                  ^
src/event/ngx_event_openssl.c:1698:34: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec'
                            c->ssl->dyn_rec.threshold)
                                  ^
src/event/ngx_event_openssl.c:1700:51: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec'
                     buf->end = buf->start + c->ssl->dyn_rec.size_hi;
                                                   ^
src/event/ngx_event_openssl.c:1703:51: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec'
                     buf->end = buf->start + c->ssl->dyn_rec.size_lo;
                                                   ^
src/event/ngx_event_openssl.c: In function 'ngx_ssl_write':
src/event/ngx_event_openssl.c:1809:15: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec_records_sent'
         c->ssl->dyn_rec_records_sent++;
               ^
src/event/ngx_event_openssl.c:1810:15: error: 'ngx_ssl_connection_t' has no member named 'dyn_rec_last_write'
         c->ssl->dyn_rec_last_write = ngx_current_msec;
               ^
objs/Makefile:920: recipe for target 'objs/src/event/ngx_event_openssl.o' failed
make[1]: **\* [objs/src/event/ngx_event_openssl.o] Error 1
make[1]: Leaving directory '/usr/src/nginx-1.11.5'
Makefile:11: recipe for target 'install' failed
make: **\* [install] Error 2

**Comment by stylersnico** [comment]
Cloudflare released a new patch for nginx 1.11.5: https://raw.githubusercontent.com/cloudflare/sslconfig/master/patches/nginx__1.11.5_dynamic_tls_records.patch

**Comment by stylersnico** [comment]
Must be solved by https://github.com/stylersnico/nginx-openssl-chacha-naxsi/commit/2555195500b06875c84b74ae3628fff3304835dc, please confirm :)

**Comment by stylersnico** [comment]
Solved
